server:
  port: ${PORT:8020}
spring:
  thymeleaf:
    mode: HTML
    cache: false  # Set to true in production
    prefix: classpath:/templates/
    suffix: .html
  flyway:
    enabled: true
    url: jdbc:postgresql://ep-tiny-thunder-ab0kaoc6-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    user: neondb_owner
    password: npg_U3Pz8ryAobWJ
    locations: classpath:db/migration
  application:
    name: antischool
  datasource:
    url: jdbc:postgresql://ep-tiny-thunder-ab0kaoc6-pooler.eu-west-2.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_U3Pz8ryAobWJ
    driver-class-name: org.postgresql.Driver
  r2dbc:
    url: r2dbc:postgresql://ep-tiny-thunder-ab0kaoc6.eu-west-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_U3Pz8ryAobWJ

logging:
  level:
    reactor.netty: DEBUG
    org.springframework.r2dbc: DEBUG
    org.telegram: DEBUG
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG
    org.springframework:

      web:
        socket: DEBUG
        reactive:
          socket: DEBUG
      messaging: DEBUG
